from enum import Enum


class ErrorCode(str, Enum):
    AUCTION_NOT_FOUND = "AUCTION_NOT_FOUND"
    BID_NOT_ALLOWED = "BID_NOT_ALLOWED"
    BUY_NOT_ALLOWED = "BUY_NOT_ALLOWED"
    AUCTION_NOT_RUNNING = "AUCTION_NOT_RUNNING"
    BID_ALREADY_EXISTS = "BID_ALREADY_EXISTS"
    INVALID_ADMIN_TOKEN = "INVALID_ADMIN_TOKEN"
    INVALID_AUCTION_STATUS = "INVALID_AUCTION_STATUS"
    INVALID_AUCTION_TIME_RANGE = "INVALID_AUCTION_TIME_RANGE"
    INVALID_AUCTION_PRICE_RULE = "INVALID_AUCTION_PRICE_RULE"
    CANNOT_RESUME_EXPIRED_AUCTION = "CANNOT_RESUME_EXPIRED_AUCTION"
    CANNOT_CANCEL_NON_RUNNING = "CANNOT_CANCEL_NON_RUNNING"
    PRODUCT_ALREADY_HAS_AUCTION = "PRODUCT_ALREADY_HAS_AUCTION"
    WINNER_NOT_FOUND = "WINNER_NOT_FOUND"
    AUTO_CHARGE_FAILED = "AUTO_CHARGE_FAILED"
